[package]
name = "ibverbs-sys"
version = "0.1.0"
edition = "2021"
authors = ["Niklas Sombert <niklas.sombert@uni-duesseldorf.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
